---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stumpy-tanker-k8s-pihole-etc-pihole-pv
  namespace: pihole
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: stumpy.co.slakin.net
    path: "/tanker/k8s/pihole-parents/etc-pihole"
  mountOptions:
      - rw
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: stumpy-tanker-k8s-pihole-etc-dnsmasq-pv
  namespace: pihole
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: stumpy.co.slakin.net
    path: "/tanker/k8s/pihole-parents/etc-dnsmasq.d"
  mountOptions:
      - rw

