---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-parents-etc-pihole-longhorn-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-parents-etc-dnsmasq-longhorn-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stumpy-tanker-k8s-pihole-etc-pihole-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  volumeName: stumpy-tanker-k8s-pihole-etc-pihole-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stumpy-tanker-k8s-pihole-etc-dnsmasq-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  volumeName: stumpy-tanker-k8s-pihole-etc-dnsmasq-pv
