---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-parents-l2-lb
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole-parents-l2-lb
  template:
    metadata:
      labels:
        app: pihole-parents-l2-lb
    spec:
      hostname: pihole-parents
      containers:
      - image: pihole/pihole:latest
        name: pihole-parents
        env:
        - name: TZ
          value: 'America/Denver'
        - name: WEBPASSWORD
          value: 'pihole'
        - name: DNSSEC
          value: 'true'
        - name: DNS_FQDN_REQUIRED
          value: 'true'
        - name: DNS_BOGUS_PRIV
          value: 'true'
        - name: PIHOLE_DNS_
          value: '1.1.1.3;1.0.0.3'
        ports:
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: pihole-parents-etc-pihole-longhorn-vol
          mountPath: /etc/pihole/
        - name: pihole-parents-etc-dnsmasq-longhorn-vol
          mountPath: /etc/dnsmasq.d/
      volumes:
      - name: pihole-parents-etc-dnsmasq-longhorn-vol
        persistentVolumeClaim:
          claimName: pihole-parents-etc-dnsmasq-longhorn-pvc
      - name: pihole-parents-etc-pihole-longhorn-vol
        persistentVolumeClaim:
          claimName: pihole-parents-etc-pihole-longhorn-pvc
