---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-parents-etc-pihole-longhorn-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 8Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-parents-etc-dnsmasq-longhorn-pvc
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
