---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: isc-dhcpd-server-pvc
  namespace: isc-dhcpd
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 100Mi
  volumeName: stumpy-nfs-isc-dhcpd-server-pv
